name: CI/CD Pipeline

env:
  USERNAME: ${{ secrets.USERNAME }}
  HOST: ${{ secrets.HOST }}
  PORT: ${{ secrets.PORT }}
  KEY: ${{ secrets.KEY }}

on:
  push:
    branches:
      - release

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          port: ${{ env.PORT }}
          script: |
            cd app
            sudo git pull origin release

  deploy:
    runs-on: ubuntu-latest
    needs: sync

    steps:
      - name: Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          port: ${{ env.PORT }}
          script: |
            sudo docker compose -f /home/${{ env.USERNAME }}/app/docker-compose.yml down --remove-orphans
            sudo docker compose -f /home/${{ env.USERNAME }}/app/docker-compose.yml up -d --build

  check:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Check containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          port: ${{ env.PORT }}
          script: |
            nc -z -v '127.0.0.1' '8001' && echo "Server is available" || echo "Server is not available"
